<?php
/* ====================================================================
 * Copyright (C) BluePex Security Solutions - All rights reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * ReWritten by Guilherme Brechot <guilherme.breachot@bluepex.com>, 2024
 *
 * ====================================================================
 *
 */

require_once("bp_control_utm_custom.inc");

if (isset($argv[1]) &&
    $argv[1] == 'help') {
	echo <<<EOF
Instructions for operating the custom UTM description tool:

Allowed parameters:
* help -> Lists the help menu;
* create -> Generates the necessary files;
* remove -> Removes files generated by the tool;
* cripty -> Generates the file used to feed the agent;
* decripty -> Gets the decrypted state of the agent usage file;
* list -> Reports the contents of the encrypted file;
* restore -> Restore txt file based on encrypted

Ex:
/usr/local/bin/php /usr/local/sbin/bp_action_utm_custom.php <action> <password>

NOTE:
* All actions require 2 parameters;
* Help is the only one that can be activated with only it as a parameter;
EOF;
	echo PHP_EOL;
	exit;
}

if (!isset($argv[1], $argv[2]) ||
    empty($argv[1]) ||
    empty($argv[2])) {
	echo "Enter the 'help' parameter to receive the information" . PHP_EOL;
	exit;
}

if (!in_array($argv[1], ['create', 'remove', 'cripty', 'decripty', 'list', 'restore']) ||
    $argv[2] != KEY_CIPHER_ACTION) {
	echo "invalid parameters" . PHP_EOL;
	exit;
}

bp_action_utm_custom_file($argv[1], $argv[2]);
